fix: adjust the implementation to the new spec version
hei-school/hei-admin-api pull request #363
Opened 2024-01-17 13:56 UTC by Iloniavo

2024-01-18 09:03 UTC, Mahefaa requested changes

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/FeeController.java
> +  }
getFeeTemplates

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/FeeController.java
> +  public List<FeeTemplate> getPredefinedFeeTypes(
getFeeTemplates

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/FeeController.java
> +  public FeeTemplate createOrUpdatePredefinedFeetype(
createOrUpdateFeeTemplates

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/FeeController.java
> +            feeTemplateService.createOrUpdateFeeTypes(feeTemplateMapper.toDomain(feeType)));
createOrUpdateFeeTemplates

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/FeeTemplateTypeEnumMapper.java
> +    }
no

2024-01-18 09:03 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/FeeTemplateTypeEnumMapper.java
> +    }
no

2024-01-18 09:03 UTC, Mahefaa commented on doc/api.yml
add getById also

2024-01-18 09:05 UTC, Iloniavo commented on doc/api.yml
Got all of it

2024-01-18 11:51 UTC, Mahefaa requested changes

2024-01-18 11:51 UTC, Mahefaa commented on src/main/java/school/hei/haapi/model/FeeTemplate.java
> +  @Enumerated(EnumType.STRING)
static import

2024-01-18 11:51 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/FeeTemplateIT.java
> +import static school.hei.haapi.integration.conf.TestUtils.*;
rm import *

2024-01-18 11:51 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/conf/TestUtils.java
> +        .type(FeeTemplate.TypeEnum.TUITION)
static import

2024-01-18 11:51 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/conf/TestUtils.java
> +        .type(CrupdateFeeTemplate.TypeEnum.TUITION);
static import

2024-01-18 11:51 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/conf/TestUtils.java
> +        .type(FeeTemplate.TypeEnum.TUITION);
static import

2024-01-18 11:51 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/FeeTemplateService.java
> +              throw new NotFoundException("{\"type\":\"404 NOT_FOUND\",\"message\":\"FeeTemplate with id: \" + id_not_existing + \" not found\"}");
() -> new NotFoundException(String);

2024-01-18 13:14 UTC, Mahefaa requested changes

2024-01-18 13:14 UTC, Mahefaa commented on doc/api.yml
> +        - REMEDIAL_COSTS
FeeTypeEnum

2024-01-18 13:14 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/FeeTemplateTypeEnumMapper.java
> +}
what ?

2024-01-18 13:14 UTC, Mahefaa commented on doc/api.yml
> +      summary: Get all templates of fee
get all fee templates

2024-01-18 13:14 UTC, Mahefaa commented on src/main/java/school/hei/haapi/model/FeeTemplate.java
> +  @Enumerated(EnumType.STRING)
static import !

2024-01-19 05:13 UTC, Mahefaa requested changes
few changes left x) good job :))

2024-01-19 05:13 UTC, Mahefaa commented on doc/api.yml
>        description: Update fee type when `id` exist, create it otherwise.
update IF exists not WHEN exists

2024-01-19 05:13 UTC, Mahefaa commented on src/main/java/school/hei/haapi/model/Fee.java
>    private school.hei.haapi.endpoint.rest.model.Fee.StatusEnum status;
try to use StatusEnum directly also here without giving the full package name

2024-01-23 11:14 UTC, Mahefaa requested changes

2024-01-23 11:14 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/FeeMapper.java
> +        return HARDWARE;
where are the other two ?

2024-01-23 11:14 UTC, Mahefaa commented on src/main/java/school/hei/haapi/repository/FeeTemplateRepository.java
> +    Optional<FeeTemplate> findById(String s);
is it really needed ??

2024-01-24 10:52 UTC, Mahefaa requested changes

2024-01-24 10:52 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/FeeTemplateService.java
> +  }
orElseThrow( () -> new NotFoundExcepton("message"));

2024-01-24 10:52 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/FeeTemplateIT.java
> +import static school.hei.haapi.integration.conf.TestUtils.*;
do not use import * !!

2024-01-24 10:52 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/FeeTemplateIT.java
> +    assertTrue(actual.contains(feeTemplate1()));
separate given when then sides with blank line

2024-01-24 10:52 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/FeeTemplateIT.java
> +    assertEquals(feeTemplate2().getNumberOfPayments(), createdFeeTemplate.getNumberOfPayments());
separate given when then sides with blank line

2024-01-24 10:52 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/FeeTemplateIT.java
> +    assertEquals(feeTemplate1(), actual);
separate given when then sides with blank line

2024-01-24 10:52 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/conf/TestUtils.java
> +
test the other types also

2024-01-24 11:36 UTC, Mahefaa requested changes

2024-01-24 11:36 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/FeeTemplateMapper.java
> +}
import the Domain with package full name but the rest with only the className

2024-01-25 10:29 UTC, Mahefaa approved these changes

2024-01-25 10:39 UTC, merged