feat: get events endpoint, filter by planner name does not work
hei-school/hei-admin-api pull request #412
Opened 2024-03-15 08:57 UTC by Iloniavo

2024-03-19 10:08 UTC, Mahefaa requested changes
add event filter by type also

2024-03-19 10:08 UTC, Mahefaa commented on doc/api.yml
> +        - name: group_id
group_ref, filters are made for humans, so we put easy values

2024-03-19 10:08 UTC, Mahefaa commented on doc/api.yml
> +      operationId: crupdateEventParticipants
does it CREATE or UPDATE ?

2024-03-19 10:08 UTC, Mahefaa commented on doc/api.yml
> +        group:
group_name ? or ref ?

2024-03-19 10:08 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/EventController.java
> +        .collect(Collectors.toUnmodifiableList());
static import

2024-03-19 10:08 UTC, Mahefaa commented on src/main/java/school/hei/haapi/model/EventParticipant.java
> +  @JoinColumn(name = "actual_group_id", referencedColumnName = "id")
why the need for "actual"

2024-03-19 10:08 UTC, Mahefaa commented on src/main/java/school/hei/haapi/repository/GroupRepository.java
>    Page<Group> getGroups(Pageable pageable);
change this. you do not need to such easy Query as @Query

2024-03-19 10:08 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/EventService.java
> +                eventParticipantService.crupdateEventParticipants(eventParticipants);
put in a public method

2024-03-19 10:08 UTC, Mahefaa commented on src/main/resources/db/migration/V0_2__Create_user_table.sql
> +    do
why indent AND MOSTLY why indent V0_2 ?

2024-03-19 10:08 UTC, Mahefaa commented on src/main/resources/db/migration/V42_19__Create_event_participant_table.sql
> +    actual_group_id varchar constraint event_participant_group_id_fk references "group"(id)
no need for 'actual' suffix

2024-03-19 10:31 UTC, Iloniavo commented on doc/api.yml
> +        group:
Group name

2024-03-19 12:05 UTC, Mahefaa requested changes

2024-03-19 12:05 UTC, Mahefaa commented on doc/api.yml
> +      summary: Create or pdate event participants
typo: pdate -> update

2024-03-19 12:05 UTC, Mahefaa commented on doc/api.yml
> +          description: Group ref of the participant
filter by group_ref

2024-03-19 12:05 UTC, Mahefaa commented on doc/api.yml
> +          description: Group ref of the participant
it is a better description

2024-03-19 12:05 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/EventController.java
> +  }
group put /events and group /events

2024-03-19 12:26 UTC, Mahefaa requested changes

2024-03-19 12:26 UTC, Mahefaa commented on src/main/java/school/hei/haapi/model/Event.java
> +  private Instant end;
use endDatetime as variable name, same for begin -> beginDatetime etc ( for api also)

2024-03-20 11:00 UTC, Mahefaa requested changes

2024-03-20 11:00 UTC, Mahefaa commented on doc/api.yml
> +      operationId: updateEventParticipants
you only update statuses so keep updateEventParticipantsStatus

2024-03-20 11:00 UTC, Mahefaa commented on doc/api.yml
> +                $ref: '#/components/schemas/CrupdateEventParticipant'
the component doesn't Crupdate

2024-03-20 12:43 UTC, merged