refactor: group and group flows resources
hei-school/hei-admin-api pull request #436
Opened 2024-04-09 12:44 UTC by haritianaadriano

* fix: fees remove payment after updating status

* feat: use batch insert between scheduler update fee status

* test: assert payment saved is not empty between late fees scheduler

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/endpoint/rest/mapper/GroupMapper.java
>          .build();
rename to students

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/model/Group.java
> +        + awardedCourse.stream().map(AwardedCourse::getId)
we do not include related entities in tostring

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/model/Group.java
> +        + groupFlows.stream().map(GroupFlow::getId)
same rq

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/service/GroupFlowService.java
> +
use services

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/service/GroupFlowService.java
> +
rm

2024-04-11 11:13 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/service/GroupService.java
>            createGroupFlows.add(
usee map

2024-04-12 10:51 UTC, Mahefaa requested changes

2024-04-12 10:51 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/GroupFlowService.java
> +  private GroupFlow mapToDomainGroupFlow(CreateGroupFlow toMap) {
rename method name to "from"

2024-04-12 10:51 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/GroupFlowService.java
> +
are these methods used ?

2024-04-12 11:40 UTC, merged