feat: add endpoint for courses with teacher
hei-school/hei-admin-api pull request #562
Opened 2024-08-07 10:55 UTC by mirado447

2024-08-07 11:20 UTC, haritianaadriano requested changes

2024-08-07 11:20 UTC, haritianaadriano commented on doc/api.yml
> +      operationId: getCoursesWithTeacher
I think get all courses assign to a teacher is more consistant

2024-08-07 11:20 UTC, haritianaadriano commented on doc/api.yml
> +      operationId: getCoursesWithTeacher
same here

2024-08-08 06:37 UTC, Mahefaa requested changes

2024-08-08 06:37 UTC, Mahefaa commented on doc/api.yml
rejected because you're forcing Teachers to tell us the entirety of the courses they teach right at their doorstep.

A possible enhancement could be to do that on a specific endpoint and cover special cases like two teachers teaching the same course but during different periods in time or even teaching the same course at the same period

2024-08-08 08:21 UTC, Iloniavo requested changes

2024-08-08 08:21 UTC, Iloniavo commented on doc/api.yml
> +                $ref: '#/components/schemas/CrupdateTeacher'
Why CrupdateTeacher instead of Teacher model

2024-08-08 08:21 UTC, Iloniavo commented on doc/api.yml
> +                  $ref: '#/components/schemas/CrupdateTeacher'
same here

2024-08-08 08:21 UTC, Iloniavo commented on doc/api.yml
> -          type: string
why is this removed ?

2024-08-08 08:34 UTC, mirado447 commented on doc/api.yml
> -          type: string
my fault, I correct taht

2024-08-08 11:33 UTC, merged