chore: GET /students multiple status filter
hei-school/hei-admin-api pull request #764
Opened 2024-12-18 13:21 UTC by kirisaki-vk

2025-01-30 07:21 UTC, haritianaadriano requested changes

2025-01-30 07:21 UTC, haritianaadriano commented on doc/api.yml
> +              $ref: '#/components/schemas/EnableStatus'
I think it's time to rename this variable. And use a better name like UserStatus or StudentStatus, EnableStatus means only ENABLE as status no ?

2025-01-30 07:21 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/endpoint/rest/controller/StudentController.java
> +        status == null ? null : status.stream().map(statusEnumMapper::toDomainStatus).toList();
handle it in the mapper method, and why you give a default value as ENABLED, SUSPENDED but you handle nullable value here ?

2025-01-30 07:21 UTC, haritianaadriano commented on src/main/java/school/hei/haapi/service/UserService.java
> +    List<User.Status> statusList = status == null ? null : List.of(status);
why you handle always the null value. But ok, i'll be fine with it but remember sometimes it's a bad things to use null as value instead it's better to use Optional or List and check if it's empty if a List and check if present if Optional

2025-01-30 07:21 UTC, haritianaadriano commented on src/test/java/school/hei/haapi/integration/StudentIT.java
> +                List.of(SUSPENDED, ENABLED, DISABLED),
and where you check Student with only two status ?

2025-01-30 09:15 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/UserService.java
> +    List<User.Status> statusList = status == null ? null : List.of(status);
if status null, List.of(), else List.of(status) a List object should never be null

2025-02-05 06:32 UTC, Mahefaa requested changes

2025-02-05 06:32 UTC, Mahefaa commented on doc/api.yml
> +              $ref: '#/components/schemas/EnableStatus'
agreed, however it will be a breaking change

2025-02-05 06:32 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/StudentController.java
> +        status == null ? null : status.stream().map(statusEnumMapper::toDomainStatus).toList();
agreed, also list variables should be named with plural nouns, hence statuses
2) a list should never be null but empty or populated.

2025-02-05 06:32 UTC, Mahefaa commented on src/main/java/school/hei/haapi/repository/dao/UserManagerDao.java
> +      List<User.Status> status,
userStatuses, static import User.Status

2025-02-05 06:32 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/StudentController.java
> +          List<EnableStatus> status,
userStatuses

2025-02-05 06:32 UTC, Mahefaa commented on src/main/java/school/hei/haapi/service/UserService.java
> +      List<User.Status> status,
userStatuses, static import User.Status

2025-02-05 06:32 UTC, Mahefaa commented on src/main/java/school/hei/haapi/endpoint/rest/controller/StudentController.java
> +          List<EnableStatus> status,
param name can be the same for retro-compatibility however you MUST change your variable names

2026-07-27 08:15 UTC, closed without merging