feat: add attendance_movement_type to Attendance
hei-school/hei-admin-api pull request #766
Opened 2024-12-19 11:53 UTC by kirisaki-vk

2025-01-09 11:34 UTC, Iloniavo requested changes

2025-01-09 11:34 UTC, Iloniavo commented on src/test/java/school/hei/haapi/integration/AttendanceIT.java
> +@Slf4j
Remove logs in test

2025-01-30 07:10 UTC, haritianaadriano approved these changes

2025-02-05 06:22 UTC, Mahefaa requested changes

2025-02-05 06:22 UTC, Mahefaa commented on src/test/java/school/hei/haapi/integration/AttendanceIT.java
>          .place(PlaceEnum.ANDRAHARO)
boyscout pattern, static import ANDRAHARO

2025-12-22 11:33 UTC, kirisaki-vk commented
Dropped

2025-12-22 11:33 UTC, closed without merging